# Generated by Django 2.2.7 on 2019-11-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('house', models.CharField(max_length=150)),
                ('sustainability_rating', models.IntegerField()),
                ('manager_diversity_rating', models.IntegerField()),
                ('alignment_rating', models.IntegerField()),
                ('inception_year', models.DateField()),
                ('performance_five', models.DecimalField(decimal_places=4, max_digits=5)),
                ('performance_ten', models.DecimalField(decimal_places=4, max_digits=5)),
                ('performance_inception', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=5)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funds', to='funds.Region')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funds', to='funds.Structure')),
                ('styles', models.ManyToManyField(related_name='funds', to='funds.Style')),
            ],
        ),
    ]
