# Generated by Django 2.2.7 on 2019-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='inception_year',
            new_name='inception_date',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='performance_five',
            new_name='y_2016',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='performance_inception',
            new_name='y_2017',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='performance_ten',
            new_name='y_2018',
        ),
        migrations.AddField(
            model_name='fund',
            name='p_and_p',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fund',
            name='people',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='stock_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2009',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2010',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2011',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2012',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2013',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2014',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='y_2015',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
