# Generated by Django 2.2.7 on 2019-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='image',
            field=models.CharField(default='', max_length=150),
        ),
    ]
