# Generated by Django 2.2.7 on 2019-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20191113_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='y_2015',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
